/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
 * Generated on: 02-Jun-2018 13:35:11
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 31
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 * Arithmetic        : fixed
 * Numerator         : s16,16 -> [-5.000000e-01 5.000000e-01)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s33,31 -> [-2 2)  (auto determined)
 *   Product         : s31,31 -> [-5.000000e-01 5.000000e-01)  (auto determined)
 *   Accumulator     : s33,31 -> [-2 2)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2017a\extern\include\tmwtypes.h 
 */
const int BL = 31;
DATA B[31] = {
        3,    -29,   -219,   -696,  -1325,  -1519,   -628,   1120,   2180,
      847,  -2495,  -4478,  -1092,   8166,  18508,  23040,  18508,   8166,
    -1092,  -4478,  -2495,    847,   2180,   1120,   -628,  -1519,  -1325,
     -696,   -219,    -29,      3
};
