/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.2 and the Signal Processing Toolbox 7.4.
 * Generated on: 19-May-2018 19:05:33
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 9
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\Programas\MATLAB\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
#define MWSPT_NSEC 19
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const int16_T NUM[MWSPT_NSEC][3] = {
  {
    15736,      0,      0 
  },
  {
    32767,      0, -32768 
  },
  {
    15736,      0,      0 
  },
  {
    32767,      0, -32768 
  },
  {
    14074,      0,      0 
  },
  {
    32767,      0, -32768 
  },
  {
    14074,      0,      0 
  },
  {
    32767,      0, -32768 
  },
  {
    13050,      0,      0 
  },
  {
    32767,      0, -32768 
  },
  {
    13050,      0,      0 
  },
  {
    32767,      0, -32768 
  },
  {
    12491,      0,      0 
  },
  {
    32767,      0, -32768 
  },
  {
    12491,      0,      0 
  },
  {
    32767,      0, -32768 
  },
  {
    12313,      0,      0 
  },
  {
    32767,      0, -32768 
  },
  {
    32767,      0,      0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const int16_T DEN[MWSPT_NSEC][3] = {
  {
    32767,      0,      0 
  },
  {
    32767, -22731,  27679 
  },
  {
    32767,      0,      0 
  },
  {
    32767,  32767,  28471 
  },
  {
    32767,      0,      0 
  },
  {
    32767,  32738,  21254 
  },
  {
    32767,      0,      0 
  },
  {
    32767, -17497,  19556 
  },
  {
    32767,      0,      0 
  },
  {
    32767,  25834,  15338 
  },
  {
    32767,      0,      0 
  },
  {
    32767, -11117,  13485 
  },
  {
    32767,      0,      0 
  },
  {
    32767,  17470,  10631 
  },
  {
    32767,      0,      0 
  },
  {
    32767,  -3022,   9356 
  },
  {
    32767,      0,      0 
  },
  {
    32767,   7182,   8141 
  },
  {
    32767,      0,      0 
  }
};
