/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.2 and the Signal Processing Toolbox 7.4.
 * Generated on: 19-May-2018 19:04:53
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 11
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
#define FILTER_SIZE 11
/* 
 * Expected path to tmwtypes.h 
 * D:\Programas\MATLAB\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int BL = FILTER_SIZE;
DATA B[FILTER_SIZE] = {
      216,   -730,    226,   3386,  -9142,  12092,  -9142,   3386,    226,
     -730,    216
};

DATA buffer[FILTER_SIZE + 2];


void filter(DATA * samplesIn, ushort numSamples, DATA * out) {
    ushort overflowFlag = fir (samplesIn, B, out, buffer, numSamples, BL);
    printf("\n\Overflow: %u\n", overflowFlag);
