/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.2 and the Signal Processing Toolbox 7.4.
 * Generated on: 19-May-2018 19:05:55
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 4
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
#define NBIQUAD 10
/* 
 * Expected path to tmwtypes.h 
 * D:\Programas\MATLAB\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
DATA filtro[5*NBIQUAD] = {
                          3514 , 7028 , 3514 , -16585 , 14256 , 3115 , 6230 , 3115 , -14702 , 10777 , 2809 , 5619 , 2809 , -13258 , 8111 , 2574 , 5148 , 2574 , -12149 , 6061 , 2394 , 4789 , 2394 , -11301 , 4494 , 2259 , 4518 , 2259 , -10662 , 3314 , 2160 , 4321 , 2160 , -10196 , 2454 , 2093 , 4187 , 2093 , -9879 , 1868 , 2054 , 4109 , 2054 , -9695 , 1528 , 5783 , 5783 , 0 , -4817 , 0
};
DATA buffer[4*NBIQUAD + 1];

void filter(DATA * samplesIn, ushort numSamples, DATA * out) {
    int i;
    DATA resized[5*NBIQUAD];
    for (i = 0; i < 4*NBIQUAD + 1; i++) buffer[i] = 0; //limpando o buffer
    for (i = 0 ; i < 5*NBIQUAD; i++) {
        if (i % 5 < 3) {
            resized[i] = (filtro[i] > 0) ? filtro[i] >> 4 : 0xF000 | filtro[i] >> 4;
        }
        else resized[i] = filtro[i];
    }
    ushort overflowFlag  = iircas51(samplesIn, resized, out, buffer, NBIQUAD, numSamples);
    printf("Overflow: %u \n", overflowFlag);
}
